name: Basic CI with Gradle (GPB IT Factory Backend 2024)
on:
  pull_request:
    branches: [ "trunk" ]
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run chmod to make gradlew executable run
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew bootRun
      - name: Test with Gradle
        run: ./gradlew test